const players = [
  {
    id: 1,
    name: "Sachin Tendulkar",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 2,
    name: "Ricky Ponting",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 3,
    name: "Jacques Kallis",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 4,
    name: "Rahul Dravid",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 5,
    name: "Alastair Cook",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 6,
    name: "Kumar Sangakkara",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 7,
    name: "Brian Lara",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 8,
    name: "Shivnarine Chanderpaul",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 9,
    name: "Mahela Jayawardene",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 10,
    name: "Joe Root",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 11,
    name: "Allan Border",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 12,
    name: "Steve Waugh",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 13,
    name: "Sunil Gavaskar",
    country: "IND)​​",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 14,
    name: "Younis Khan",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 15,
    name: "Steven Smith",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 16,
    name: "Hashim Amla",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 17,
    name: "Graeme Smith",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 18,
    name: "Graham Gooch",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 19,
    name: "Virat Kohli",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 20,
    name: "Javed Miandad",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 21,
    name: "Inzamam-ul-Haq",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 22,
    name: "David Warner",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 23,
    name: "VVS Laxman",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 24,
    name: "AB de Villiers",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 25,
    name: "Michael Clarke",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 26,
    name: "Matthew Hayden",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 27,
    name: "Virender Sehwag",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 28,
    name: "Vivian Richards",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 29,
    name: "Alec Stewart",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 30,
    name: "Kane Williamson",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 31,
    name: "David Gower",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 32,
    name: "Kevin Pietersen",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 33,
    name: "Geoffrey Boycott",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 34,
    name: "Garfield Sobers",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 35,
    name: "Mark Waugh",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 36,
    name: "Michael Atherton",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 37,
    name: "Ian Bell",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 38,
    name: "Justin Langer",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 39,
    name: "Ross Taylor",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 40,
    name: "Colin Cowdrey",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 41,
    name: "Gordon Greenidge",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 42,
    name: "Mohammad Yousuf",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 43,
    name: "Mark Taylor",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 44,
    name: "Clive Lloyd",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 45,
    name: "Desmond Haynes",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 46,
    name: "David Boon",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 47,
    name: "Angelo Mathews",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 48,
    name: "Gary Kirsten",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 49,
    name: "Wally Hammond",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 50,
    name: "Chris Gayle",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 51,
    name: "Sourav Ganguly",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 52,
    name: "Cheteshwar Pujara",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 53,
    name: "Stephen Fleming",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 54,
    name: "Azhar Ali",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 55,
    name: "Greg Chappell",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 56,
    name: "Andrew Strauss",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 57,
    name: "Donald Bradman",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 58,
    name: "Sanath Jayasuriya",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 59,
    name: "Len Hutton",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 60,
    name: "Dilip Vengsarkar",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 61,
    name: "Ken Barrington",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 62,
    name: "Graham Thorpe",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 63,
    name: "Dimuth Karunaratne",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 64,
    name: "Brendon McCullum",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 65,
    name: "Aravinda de Silva",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 66,
    name: "Michael Hussey",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 67,
    name: "Rohan Kanhai",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 68,
    name: "Mohammad Azharuddin",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 69,
    name: "Herschelle Gibbs",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 70,
    name: "Neil Harvey",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 71,
    name: "Ben Stokes",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 72,
    name: "Gundappa Viswanath",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 73,
    name: "Richie Richardson",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 74,
    name: "Ramnaresh Sarwan",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 75,
    name: "Marcus Trescothick",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 76,
    name: "Denis Compton",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 77,
    name: "Jonny Bairstow",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 78,
    name: "Saleem Malik",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 79,
    name: "Nasser Hussain",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 80,
    name: "Carl Hooper",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 81,
    name: "Michael Vaughan",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 82,
    name: "Mushfiqur Rahim",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 83,
    name: "Adam Gilchrist",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 84,
    name: "Mark Boucher",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 85,
    name: "Marvan Atapattu",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 86,
    name: "Kraigg Brathwaite",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 87,
    name: "Tillakaratne Dilshan",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 88,
    name: "Thilan Samaraweera",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 89,
    name: "Martin Crowe",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 90,
    name: "Jack Hobbs",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 91,
    name: "Kim Hughes",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 92,
    name: "Dean Elgar",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 93,
    name: "Ian Chappell",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 94,
    name: "John Wright",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 95,
    name: "Michael Slater",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 96,
    name: "Dinesh Chandimal",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 97,
    name: "Usman Khawaja",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 98,
    name: "Kapil Dev",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 99,
    name: "Bill Lawry",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 100,
    name: "Misbah-ul-Haq",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 101,
    name: "Muttiah Muralitharan",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 102,
    name: "Shane Warne",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 103,
    name: "James Anderson",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 104,
    name: "Anil Kumble",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 105,
    name: "Stuart Broad",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 106,
    name: "Glenn McGrath",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 107,
    name: "Courtney Walsh",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 108,
    name: "Nathan Lyon",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 109,
    name: "Ravichandran Ashwin",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 110,
    name: "Dale Steyn",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 111,
    name: "Rangana Herath",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 112,
    name: "Sir Richard Hadlee",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 113,
    name: "Shaun Pollock",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 114,
    name: "Harbhajan Singh",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 115,
    name: "Wasim Akram",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 116,
    name: "Curtly Ambrose",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 117,
    name: "Makhaya Ntini",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 118,
    name: "Ian Botham",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 119,
    name: "Malcolm Marshall",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 120,
    name: "Tim Southee",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 121,
    name: "Waqar Younis",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 122,
    name: "Imran Khan",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 123,
    name: "Daniel Vettori",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 124,
    name: "Dennis Lillee",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 125,
    name: "Chaminda Vaas",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 126,
    name: "Mitchell Starc",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 127,
    name: "Allan Donald",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 128,
    name: "Bob Willis",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 129,
    name: "Trent Boult",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 130,
    name: "Mitchell Johnson",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 131,
    name: "Zaheer Khan",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 132,
    name: "Ishant Sharma",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 133,
    name: "Brett Lee",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 134,
    name: "Lance Gibbs",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 135,
    name: "Morne Morkel",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 136,
    name: "Fred Trueman",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 137,
    name: "Derek Underwood",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 138,
    name: "Craig McDermott",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 139,
    name: "Kagiso Rabada",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 140,
    name: "Ravindra Jadeja",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 141,
    name: "Kemar Roach",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 142,
    name: "Bishan Singh Bedi",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 143,
    name: "Pat Cummins",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 144,
    name: "Danish Kaneria",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 145,
    name: "Joel Garner",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 146,
    name: "Jason Gillespie",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 147,
    name: "Josh Hazlewood",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 148,
    name: "Neil Wagner",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 149,
    name: "Graeme Swann",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 150,
    name: "Brian Statham",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 151,
    name: "Michael Holding",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 152,
    name: "Richie Benaud",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 153,
    name: "Matthew Hoggard",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 154,
    name: "Graham McKenzie",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 155,
    name: "Yasir Shah",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 156,
    name: "Bhagwat Chandrasekhar",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 157,
    name: "Abdul Qadir",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 158,
    name: "Alec Bedser",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 159,
    name: "Javagal Srinath",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 160,
    name: "Gary Sobers",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 161,
    name: "Andy Caddick",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 162,
    name: "Chris Martin",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 163,
    name: "Shakib Al Hasan",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 164,
    name: "Darren Gough",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 165,
    name: "Mohammed Shami",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 166,
    name: "Ray Lindwall",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 167,
    name: "Andrew Flintoff",
    country: "ICC",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 168,
    name: "Steve Harmison",
    country: "ICC",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 169,
    name: "Vernon Philander",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 170,
    name: "Peter Siddle",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 171,
    name: "Chris Cairns",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 172,
    name: "Clarrie Grimmett",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 173,
    name: "Heath Streak",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 174,
    name: "Merv Hughes",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 175,
    name: "Stuart MacGill",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 176,
    name: "Saqlain Mushtaq",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 177,
    name: "Moeen Ali",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 178,
    name: "Andy Roberts",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 179,
    name: "John Snow",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 180,
    name: "Jeff Thomson",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 181,
    name: "Jim Laker",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 182,
    name: "Wes Hall",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 183,
    name: "Taijul Islam",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 184,
    name: "Sydney Barnes",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 185,
    name: "Erapalli Prasanna",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 186,
    name: "Alan Davidson",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 187,
    name: "Mushtaq Ahmed",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 188,
    name: "Geoff Lawson",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 189,
    name: "Saeed Ajmal",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 190,
    name: "Shoaib Akhtar",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 191,
    name: "Angus Fraser",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 192,
    name: "Sarfraz Nawaz",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 193,
    name: "Tony Lock",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 194,
    name: "Iqbal Qasim",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 195,
    name: "Suranga Lakmal",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 196,
    name: "Terry Alderman",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 197,
    name: "Keith Miller",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 198,
    name: "Shahid Afridi",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 199,
    name: "Lasith Malinga",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 200,
    name: "Ajit Agarkar",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 201,
    name: "Mashrafe Mortaza",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 202,
    name: "Abdul Razzaq",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 203,
    name: "Kyle Mills",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 204,
    name: "Abdur Razzak",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 205,
    name: "Chris Harris",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 206,
    name: "Dwayne Bravo",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 207,
    name: "Nuwan Kulasekara",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 208,
    name: "Adil Rashid",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 209,
    name: "Venkatesh Prasad",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 210,
    name: "Lance Klusener",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 211,
    name: "Chamara Fernando",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 212,
    name: "Rashid Khan",
    country: "AFG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 213,
    name: "Aaqib Javed",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 214,
    name: "Umar Gul",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 215,
    name: "Thisara Perera",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 216,
    name: "Nathan Bracken",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 217,
    name: "Imran Tahir",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 218,
    name: "Jacob Oram",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 219,
    name: "Irfan Pathan",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 220,
    name: "Chris Woakes",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 221,
    name: "Kuldeep Yadav",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 222,
    name: "Shane Watson",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 223,
    name: "Adam Zampa",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 224,
    name: "Mohammad Nabi",
    country: "AFG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 225,
    name: "Mustafizur Rahman",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 226,
    name: "Jason Holder",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 227,
    name: "Shoaib Malik",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 228,
    name: "Ashish Nehra",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 229,
    name: "Manoj Prabhakar",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 230,
    name: "Brad Hogg",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 231,
    name: "Ajantha Mendis",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 232,
    name: "Upul Chandana",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 233,
    name: "Jasprit Bumrah",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 234,
    name: "Shane Bond",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 235,
    name: "Thomas Odoyo",
    country: "KENYA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 236,
    name: "Matt Henry",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 237,
    name: "Bhuvneshwar Kumar",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 238,
    name: "Ewen Chatfield",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 239,
    name: "Mohammad Hafeez",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 240,
    name: "Kumar Dharmasena",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 241,
    name: "Scott Styris",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 242,
    name: "Farveez Maharoof",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 243,
    name: "Liam Plunkett",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 244,
    name: "Ish Sodhi",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 245,
    name: "Mitchell Santner",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 246,
    name: "Shadab Khan",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 247,
    name: "Mark Adair",
    country: "IRE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 248,
    name: "Wanindu Hasaranga",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 249,
    name: "Sandeep Lamichhane",
    country: "NEP",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 250,
    name: "Yuzvendra Chahal",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 251,
    name: "Chris Jordan",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 252,
    name: "Shem Ngoche",
    country: "KENYA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 253,
    name: "Bilal Khan",
    country: "OMA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 254,
    name: "Haris Rauf",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 255,
    name: "Henry Ssenyondo",
    country: "UGA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 256,
    name: "George Dockrell",
    country: "IRE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 257,
    name: "Karan KC",
    country: "NEP",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 258,
    name: "Tabraiz Shamsi",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 259,
    name: "Kevin Irakoze",
    country: "RWN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 260,
    name: "Hardik Pandya",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 261,
    name: "Shaheen Shah Afridi",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 262,
    name: "Aizaz Khan",
    country: "HKG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 263,
    name: "Josh Little",
    country: "IRE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 264,
    name: "Safyaan Sharif",
    country: "SCOT",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 265,
    name: "Zahoor Khan",
    country: "UAE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 266,
    name: "Moses Akayezu",
    country: "RWN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 267,
    name: "Dinesh Maisuria",
    country: "BOT",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 268,
    name: "Mark Watt",
    country: "SCOT",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 269,
    name: "Ehsan Khan",
    country: "HKG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 270,
    name: "Dinesh Nakrani",
    country: "UGA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 271,
    name: "Imad Wasim",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 272,
    name: "Craig Young",
    country: "IRE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 273,
    name: "Avinash Bohara",
    country: "NEP",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 274,
    name: "Paul van Meekeren",
    country: "NED",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 275,
    name: "Arshdeep Singh",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 276,
    name: "Bilal Hassun",
    country: "UGA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 277,
    name: "Tendai Chatara",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 278,
    name: "Rohan Mustafa",
    country: "UAE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 279,
    name: "Eric Sebareme",
    country: "RWN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 280,
    name: "Zephaniah Bimenyimana",
    country: "RWN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 281,
    name: "Jan Frylinck",
    country: "NAM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 282,
    name: "Hasan Ali",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 283,
    name: "Lungi Ngidi",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 284,
    name: "Yalinde Nkanya",
    country: "TAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 285,
    name: "Alvin Ramjani",
    country: "UGA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 286,
    name: "Norman Vanua",
    country: "PNG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 287,
    name: "Vraj Patel",
    country: "KENYA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 288,
    name: "Mohammad Amir",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 289,
    name: "Richard Ngarava",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 290,
    name: "Wayne Parnell",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 291,
    name: "Waseem Abbas",
    country: "MLT",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 292,
    name: "Luke Jongwe",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 293,
    name: "Junaid Siddique",
    country: "UAE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 294,
    name: "Nathan McCullum",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 295,
    name: "Mujeeb Ur Rahman",
    country: "AFG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 296,
    name: "Kevin O'Brien",
    country: "IRE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 297,
    name: "Pieter Seelaar",
    country: "NED",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 298,
    name: "Sikandar Raza",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 299,
    name: "Adam Milne",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 300,
    name: "Samuel Badree",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 301,
    name: "Roelof van der Merwe",
    country: "NED/SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 302,
    name: "Dushmantha Chameera",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 303,
    name: "Frank Nsubuga",
    country: "UGA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 304,
    name: "Charles Perchard",
    country: "JER",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 305,
    name: "Boyd Rankin",
    country: "ENG/IRE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 306,
    name: "Pavandeep Singh",
    country: "MAL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 307,
    name: "Bernard Scholtz",
    country: "NAM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 308,
    name: "Sohail Tanvir",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 309,
    name: "Abishek Kimote",
    country: "TAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 310,
    name: "Blessing Muzarabani",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 311,
    name: "Mohammed Aslam",
    country: "KUW",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 312,
    name: "Sheldon Cottrell",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 313,
    name: "Muslim Yar",
    country: "GER",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 314,
    name: "Sunil Narine",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 315,
    name: "Rohit Sharma",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 316,
    name: "Babar Azam",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 317,
    name: "Martin Guptill",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 318,
    name: "Paul Stirling",
    country: "IRE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 319,
    name: "Aaron Finch",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 320,
    name: "Mohammad Rizwan",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 321,
    name: "Jos Buttler",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 322,
    name: "Eoin Morgan",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 323,
    name: "Quinton de Kock",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 324,
    name: "Glenn Maxwell",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 325,
    name: "David Miller",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 326,
    name: "KL Rahul",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 327,
    name: "Suryakumar Yadav",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 328,
    name: "Mahmudullah",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 329,
    name: "Andrew Balbirnie",
    country: "IRE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 330,
    name: "Alex Hales",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 331,
    name: "Mohammad Shahzad",
    country: "AFG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 332,
    name: "Richie Berrington",
    country: "SCOT",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 333,
    name: "Virandeep Singh",
    country: "MAL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 334,
    name: "JP Duminy",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 335,
    name: "Simon Ssesazi",
    country: "UGA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 336,
    name: "Dawid Malan",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 337,
    name: "Nicholas Pooran",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 338,
    name: "Najibullah Zadran",
    country: "AFG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 339,
    name: "Shikhar Dhawan",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 340,
    name: "Syed Aziz",
    country: "MAL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 341,
    name: "Tamim Iqbal",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 342,
    name: "Colin Munro",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 343,
    name: "Glenn Phillips",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 344,
    name: "Litton Das",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 345,
    name: "Reeza Hendricks",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 346,
    name: "Sean Williams",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 347,
    name: "Umar Akmal",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 348,
    name: "Kusal Perera",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 349,
    name: "George Munsey",
    country: "SCOT",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 350,
    name: "Collins Obuya",
    country: "KENYA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 351,
    name: "Hamilton Masakadza",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 352,
    name: "Muhammad Waseem",
    country: "UAE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 353,
    name: "MS Dhoni",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 354,
    name: "Marlon Samuels",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 355,
    name: "Suresh Raina",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 356,
    name: "Max O'Dowd",
    country: "NED",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 357,
    name: "Kieron Pollard",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 358,
    name: "Fakhar Zaman",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 359,
    name: "Faf du Plessis",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 360,
    name: "Lendl Simmons",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 361,
    name: "Jason Roy",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 362,
    name: "Kyle Coetzer",
    country: "SCOT",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 363,
    name: "Ahmed Shehzad",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 364,
    name: "Evin Lewis",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 365,
    name: "Tony Ura",
    country: "PNG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 366,
    name: "Craig Ervine",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 367,
    name: "Dasun Shanaka",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 368,
    name: "Asghar Afghan",
    country: "AFG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 369,
    name: "Mark Chapman",
    country: "HKG/NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 370,
    name: "Issa Selemani",
    country: "TAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 371,
    name: "Ahmed Faiz",
    country: "MAL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 372,
    name: "Dipendra Singh Airee",
    country: "NEP",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 373,
    name: "Ravija Sandaruwan",
    country: "KUW",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 374,
    name: "Kusal Mendis",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 375,
    name: "Devon Conway",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 376,
    name: "Mitchell Marsh",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 377,
    name: "Rahmanullah Gurbaz",
    country: "AFG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 378,
    name: "Nizakat Khan",
    country: "HKG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 379,
    name: "Gary Wilson",
    country: "IRE",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 380,
    name: "Daryl Mitchell",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 381,
    name: "Babar Hayat",
    country: "HKG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 382,
    name: "Ben Cooper",
    country: "NED",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 383,
    name: "Calum MacLeod",
    country: "SCOT",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 384,
    name: "Soumya Sarkar",
    country: "BAN",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 385,
    name: "Irfan Karim",
    country: "KENYA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 386,
    name: "Rovman Powell",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 387,
    name: "Riazat Ali Shah",
    country: "UGA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 388,
    name: "Tim Seifert",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 389,
    name: "Robert Satheesan",
    country: "ROM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 390,
    name: "Saeed Anwar",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 391,
    name: "Yuvraj Singh",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 392,
    name: "Arjuna Ranatunga",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 393,
    name: "Nathan Astle",
    country: "NZ",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 394,
    name: "Upul Tharanga",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 395,
    name: "Michael Bevan",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 396,
    name: "Andy Flower",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 397,
    name: "Viv Richards",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 398,
    name: "Brendan Taylor",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 399,
    name: "Grant Flower",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 400,
    name: "Ijaz Ahmed",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 401,
    name: "Dean Jones",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 402,
    name: "Jonty Rhodes",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 403,
    name: "Ramiz Raja",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 404,
    name: "Hansie Cronje",
    country: "SA",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 405,
    name: "Ajay Jadeja",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 406,
    name: "Steve Smith",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 407,
    name: "Damien Martyn",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 408,
    name: "Gautam Gambhir",
    country: "IND",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 409,
    name: "Alistair Campbell",
    country: "ZIM",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 410,
    name: "Roshan Mahanama",
    country: "SL",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 411,
    name: "Shai Hope",
    country: "WI",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 412,
    name: "Paul Collingwood",
    country: "ENG",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 413,
    name: "Andrew Symonds",
    country: "AUS",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
  {
    id: 414,
    name: "Aamer Sohail",
    country: "PAK",
    batting_hand: "right",
    bowling_arm: "right",
    bowling_type: "seam",
  },
];
module.exports = players;